# [[dein.toml]]

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'preservim/nerdtree'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = '4513ECHO/vim-colors-hatsunemiku'

[[plugins]]
repo = 'junegunn/fzf'
build_on = '''
./install -all
'''
[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'


